### PR TITLE
Asciidoc to html

### PR DESCRIPTION
**Pull request by thomasbuechi**

### CODE REVIEW

**Comment by thomasbuechi** [comment]
Hey @hendrikebbers 
As of now we render the websites once we build the application with a maven plugin -> see pom.xml line 61-183
The html files are generated in the target folder and used from there.
-> View Deployment

This seems like a better solution than render them during runtime.
What is your opinion on this?

**Comment by aahlenst** [comment]
@thomasbuechi What's the difference between "this is the link" and "presentation file" apart from the different URLs and that one shows pictures and the other does not?

**Comment by thomasbuechi** [comment]
@aahlenst I renamed the first link to "AsciiDoc Article Template" which we copied from https://asciidoctor.org/docs/asciidoc-article/ 
The second one called "presentation" was a test on how to set up a page on my own with help of the documentation.

**Comment by hiddenmind3** [comment]
closed. Doesn't fulfil Project Owners expectations. The corresponding UserStory #17 has been updated

**Pull request closed without merging**
